on:
  workflow_dispatch:

jobs:
  build:
    name: Build GEM
    runs-on: jruby
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: bundle install

      - name: Build plugin
        run: gem build logstash-input-s3-sns-sqs.gemspec

      - name: Release GEM
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            *.gem

