name: Release
run-name: "Release GEM"

on:
  release:
    types: [created]

jobs:
  build:
    name: Build GEM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "jruby"
          bundler-cache: true

      - name: Build plugin
        run: gem build logstash-input-s3-sns-sqs.gemspec

      - name: Release GEM
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          prerelease: true
          file_glob: true
          file: ./*.gem

